site_name: Acessibilidade++
site_url: https://henriquecq.github.io/Acessibilidade_pp/
theme:
  name: material
  logo: imagens/logo.png
  language: pt
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  extra:
    toc: false

plugins:
  - search
  - tags

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption
  

extra_javascript:
  - js/checklist.js

extra_css:
  - css/checklist.css

nav:
  - Sobre: index.md
  - Desenvolvimento Web: desenvolvimento/desenvolvimento_web.md
  - Design: design/design.md
  - Conteúdo: conteudo/conteudo.md
  - Gestão de Projetos: gp/gestao_de_projetos.md
  - Ferramentas: ferramentas/ferramentas.md

    

