site_name: Guia de Acessibilidade do Vestibulando
site_url: https://henriquecq.github.io/Guia_de_Acessibilidade-IHC/
theme:
  name: material
  palette: 
    - scheme: red
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  #- tags

nav:
  - Sobre: guia.md
  - Desenvolvimento Web: Desenvolvimento_web/desenvolvimento_web.md
  - Design: Design/design.md
  - Conteúdo: Conteudo/conteudo.md
  - Gestão de Projetos: Gestao_de_Projetos/gestao_de_projetos.md
  - Ferramentas: Ferramentas/ferramentas.md

    

